// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite3

type GameState struct {
	ID           int64
	Code         string
	Name         string
	Description  string
	TurnNumber   int64
	GalaxyRadius int64
	NumSpecies   int64
	NumStars     int64
	NumPlanets   int64
	PrngSeed     int64
}
