// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: server.sql

package sqlite3

import (
	"context"
)

const getServerPaths = `-- name: GetServerPaths :one


SELECT code, name
FROM game_state
`

type GetServerPathsRow struct {
	Code string
	Name string
}

//	Copyright (c) 2024 Michael D Henderson. All rights reserved.
//
// GetGameState returns the game state.
func (q *Queries) GetServerPaths(ctx context.Context) (GetServerPathsRow, error) {
	row := q.db.QueryRowContext(ctx, getServerPaths)
	var i GetServerPathsRow
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}
